services:
  # Service PHP-FPM
  app:
    build: .
    volumes:
      # Mount avec le flag :cached pour de meilleures performances
      - ./src:/var/www/html:cached
      # Volumes nommés pour les dépendances (évite les problèmes de performances)
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    environment:
      - DOCKER_BUILDKIT=1
      # Variables d'environnement pour le développement
      - APP_ENV=local
      - PHP_IDE_CONFIG=serverName=docker
    env_file:
      - src/.env
    ports:
      - "9000:9000"
    command: php-fpm

  # Service pour Vite (serveur de développement)
  vite:
    build: 
      context: .
      dockerfile: docker/vite/Dockerfile
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./src:/var/www/html:cached
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    depends_on:
      - app

  # Serveur web Nginx reverse proxy (plus léger qu'Apache)
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # Base de données
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql   
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

volumes:
  vendor:
  node_modules:
  mysql: 